version: '3'
services:
  bloghook:
    image: leafney/hexo-webhook:latest
    container_name: bloghook
    restart: always
    ports:
      - "127.0.0.1:8665:80" # hexo blog
      - "127.0.0.1:8666:8080" # gin webhook
    environment:
      - CLONE_URL=https://github.com/Leafney/Leafney.github.io.git